"""again fix relation problem

Revision ID: 0847a5148feb
Revises: 6f1e0e95a6de
Create Date: 2024-10-09 18:59:15.649500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0847a5148feb'
down_revision: Union[str, None] = '6f1e0e95a6de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pictures_tag_fkey', 'pictures', type_='foreignkey')
    op.drop_column('pictures', 'tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('pictures_tag_fkey', 'pictures', 'tags', ['tag'], ['name'])
    # ### end Alembic commands ###
