"""add paid

Revision ID: 0b6e18b880f0
Revises: b6ab7fcc0f34
Create Date: 2024-11-04 14:50:50.170526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6e18b880f0'
down_revision: Union[str, None] = 'b6ab7fcc0f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('paid', sa.Boolean(), nullable=False))
    op.alter_column('payments', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.alter_column('payments', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('payments', 'paid')
    # ### end Alembic commands ###
