"""Initial migration

Revision ID: 39ee78318356
Revises: 
Create Date: 2024-09-30 11:20:42.051662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ee78318356'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('user_tg_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pictures', 'users', ['user_tg_id'], ['tg_id'])
    op.drop_column('pictures', 'users.tg_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('users.tg_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pictures', type_='foreignkey')
    op.drop_column('pictures', 'user_tg_id')
    # ### end Alembic commands ###
