"""fix relation problem

Revision ID: 6f1e0e95a6de
Revises: 0b1f7b07b89a
Create Date: 2024-10-09 18:57:51.833031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1e0e95a6de'
down_revision: Union[str, None] = '0b1f7b07b89a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pictures', 'tags', ['tag'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pictures', type_='foreignkey')
    # ### end Alembic commands ###
