"""add payment

Revision ID: b6ab7fcc0f34
Revises: b3acb6799237
Create Date: 2024-10-30 07:00:43.677318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ab7fcc0f34'
down_revision: Union[str, None] = 'b3acb6799237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('payments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('order_id', sa.String(), nullable=False))
    op.add_column('payments', sa.Column('total_amount', sa.Integer(), nullable=False))
    op.drop_column('payments', 'amount')
    op.drop_column('payments', 'is_paid')
    op.add_column('pictures', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pictures', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pictures', type_='foreignkey')
    op.drop_column('pictures', 'payment_id')
    op.add_column('payments', sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('payments', 'total_amount')
    op.drop_column('payments', 'order_id')
    op.drop_column('payments', 'user_id')
    op.drop_table('donations')
    # ### end Alembic commands ###
